### ISSUE TITLE
[JOSS] Community guidelines - add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by EmilyBourne** [SGpp/DisCoTec#127]
Regarding  https://github.com/openjournals/joss-reviews/issues/7018 - "Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support"

I recommend adding a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file to the repository to outline how others might contribute to this repository.

**Comment by freifrauvonbleifrei** [comment]
As part of the README / Docs restructuring, I bundled this CONTRIBUTING.md file:
<https://github.com/SGpp/DisCoTec/blob/feature_documentation/CONTRIBUTING.md>
Let me know what you think!

**Comment by EmilyBourne** [comment]
This looks good to me :+1:
