### ISSUE TITLE
[JOSS] Contributing and authorship

### ISSUE THREAD

**Issue by EmilyBourne** [SGpp/DisCoTec#128]
Regarding https://github.com/openjournals/joss-reviews/issues/7018 - "Contribution and authorship: Has the submitting author (@freifrauvonbleifrei) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?"

I noticed on the [contributors page](https://github.com/SGpp/DisCoTec/graphs/contributors) that there seem to be 10 authors of the code (of which at least 4 seem to be major authors):
![image](https://github.com/user-attachments/assets/ae9b21f6-e427-4900-96d2-9686acd082aa)

but there are only 3 authors of the paper. I can identify the first 2 authors. Is @hurlerml Dirk Pflüger? Is it normal that Michael Obersteiner (@obersteiner ) is not listed as an author?

**Comment by freifrauvonbleifrei** [comment]
as far as I know, @hurlerml (a student contributor) is not at Uni Stuttgart any more, so I don't know if he'll react. But looking at the contributors page, I would agree that both @hurlerml and @obersteiner  should both at least have the chance to be authors.

@hurlerml @obersteiner would you like to? -> current paper draft is here: https://github.com/SGpp/DisCoTec/blob/feature_joss_submission/paper.md  (authors can be added in the metadata)

**Comment by hurlerml** [comment]
Thank you for reaching out and for considering me as an author. I'm glad to hear that the code is being published to the Journal of Open Source Software. I would be happy to be mentioned. Please feel free to include me as an author.

Best regards,
Marcel

**Comment by freifrauvonbleifrei** [comment]
@hurlerml , I just saw your comment now, happy to hear from you! I just added you to the authors, let me know in case you want an ORCID added :)

**Comment by freifrauvonbleifrei** [comment]
Yay, with commit 65a03913b658370a9787987991dd854b8683960e we have added all major contributors!
